### ISSUE TITLE
Miniaturized photos in the album doesn't take the "Orientation" exif field into account

### ISSUE THREAD

**Issue by NicsTr** [Frky/polaroid#1]
Photos originally taken in portrait mode are, in the album, displayed in landscape mode.
That may be because the miniaturized photos loses all exif data (especially the "Orientation" field) that exist in the original photo.

**Comment by Frky** [comment]
I strongly believe that the reason of this issue is not the one you suggest. Indeed, most of the pictures, even miniaturised, are displayed in portrait mode when they should. However there seems to be an issue with some specific exif tag (probably the geometric orientation of the camera, in degree, when the picture was taken).

**Comment by NicsTr** [comment]
Commit c7a07705ee57905112ee018260dd6ae32f116db1 fixed it.
